Add ECR repository construct
citizensadvice/ca-cdk-constructs pull request #33
Opened 2023-08-18 14:20 UTC by MatthewCane

## Describe your changes

Add an ECR repository construct with defaults tailored to the image tagging policy.

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have updated the Readme / docs
- [ ] If this is a breaking change, I have discussed the roll-out and roll-back plan with the team(s) and I have provided detailed instructions
- [ ] If it is a core feature, I have added thorough tests

2023-08-21 12:54 UTC, MatthewCane commented
I have no idea why the tests are failing in CI, they work perfectly well locally.

2023-08-21 16:19 UTC, ruthwells commented
Is it also worth adding the stack output with the command that you need to run for the scan results (see infra-components). a bit like we do for the lwac commands or the helm diffs?

2023-08-22 09:04 UTC, MatthewCane commented
Sounds like a reasonable feature!

2023-08-22 14:57 UTC, MatthewCane commented
@ruthwells I've added a stack output

2023-08-22 17:12 UTC, ruthwells commented
Hi @MatthewCane I was actually thinking about this output [here](https://github.com/citizensadvice/infra-components/blob/develop/resources/templates/cloudformation_ruby_dsl/beanstalk/ecr.rb#L73) which gives you the command to get scan outputs? But maybe that's overkill?

2023-08-22 19:18 UTC, MatthewCane commented
Oh I see what you mean @ruthwells! I think that has a place but not here I don't think. As a pre-written Action, absolutely.

2023-09-06 09:43 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +        lifecycle_rules.append(
let's list the rules in priority order (lowest to highest) as this is how they are evaluated

2023-09-06 09:44 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +                description="Delete development images after 90 days year",
a whole Mercurian year and a bit more!

2023-09-06 09:46 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +                tag_prefix_list=["dev_"],
I would the that prefix an instance attribute that defaults to `dev_`

2023-09-06 09:48 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +        for account in additional_accounts_pull:
I don't think it's worth having these here as we have direct access to `self.repository` outside the object

2023-09-06 09:50 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +        if outputs_enabled:
IMO constructs shouldn't define outputs as the output name will change depending on which stack the construct is used in; also, adding the output is trivial and can be easily done outside of the class

2023-09-06 09:51 UTC, zhelyan commented on ca_cdk_constructs/ecr/ecr_repository.py
> +        lifecycle_rules += additional_lifecycle_rules
no need to do that as we can set them with `EcrRepository(......).repository.add_lifecycle_rule(....)`

2023-09-06 09:52 UTC, zhelyan requested changes
see comments

2023-09-06 11:29 UTC, Shaqil1989 commented on ca_cdk_constructs/ecr/ecr_repository.py
> +    :param scan_on_push: Whether to scan for vulnerabilities on the image on push. Defaults to True.
At least the `outputs_enabled` property is missing above, and should the order of all of the `:param` above be the same as the below in the `__init__`

2023-09-06 13:01 UTC, MatthewCane commented
@zhelyan & @Shaqil1989 I have addressed all the comments, could I please have a re-review 🙂

2023-09-06 13:05 UTC, zhelyan approved these changes

2023-09-06 13:09 UTC, zhelyan requested changes
update the tests. Actually there's no point testing the construct as there's no custom logic at all.

2023-09-06 15:22 UTC, Shaqil1989 reviewed
Looks good to me regarding the comments i made before.

2023-09-07 07:27 UTC, MatthewCane commented
@zhelyan done!

2023-09-07 08:24 UTC, merged